### ISSUE TITLE
Inspecting store with DevTools results in this.todos undefined

### ISSUE THREAD

**Issue by darkdark87** [ryanatkn/react-mobx-typescript-experiments#1]
Hi,

Accessed your demo here: https://ryanatkn.github.io/react-mobx-typescript-experiments/#/todos?_k=3pjoui
and tried to inspect the contents of the todoStore using DevTools. Received the following errors in the console:

![image](https://user-images.githubusercontent.com/765468/32406155-719f3924-c173-11e7-8dfc-44c5e2161e53.png)

"TypeError: this.todos is undefined"
"Error: [mobx] Invariant failed: Cycle detected in computation ObservableObject@14.completedTodos in 'function(){return this.todos.filter(function(e){return e.isComplete})}'"

Any idea what could be wrong? The example seems to work, so I'm unsure if the error is in DevTools itself or the communication between MobX and MobX Devtools..

**Comment by ryanatkn** [comment]
Thanks for the report. Are you running the dev tools with this [browser extension](https://github.com/andykog/mobx-devtools), or a local manual installation that you added to the code yourself, or something else? The browser extension requires a newer version of MobX and mobx-react than this project uses, and it doesn't load at all for me.

I recently started using MobX in a new project, so maybe it's about time to update this project to the latest versions.

**Comment by ryanatkn** [comment]
Thanks for the report. Are you running the dev tools with a local manual installation that you added to the code yourself, or this [browser extension](https://github.com/andykog/mobx-devtools), or something else? The browser extension requires a newer version of MobX and mobx-react than this project uses, and it doesn't load at all for me.

I recently started using MobX in a new project, so maybe it's about time to update this project to the latest versions.

**Comment by darkdark87** [comment]
Thanks for getting back to me. Turns out that I was using the wrong browser extension. With the one you linked to I can easily inspect my mobx stores.
Thank you.
